// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq9rw1IQzYa96BfzoGYfIlr63rU622evs',
    appId: '1:74651827398:web:ad03df228a3e02d2c5abc7',
    messagingSenderId: '74651827398',
    projectId: 'flutter-projects-defcc',
    authDomain: 'flutter-projects-defcc.firebaseapp.com',
    storageBucket: 'flutter-projects-defcc.appspot.com',
    measurementId: 'G-4KQPCL0NP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdnZMYhfjus-vbgtGhkHLcovTXZju7Oc',
    appId: '1:74651827398:android:a0650e207724f836c5abc7',
    messagingSenderId: '74651827398',
    projectId: 'flutter-projects-defcc',
    storageBucket: 'flutter-projects-defcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu4ePmf2Dxy4dZLD2wyE1T8dCudAt6wvc',
    appId: '1:74651827398:ios:27dcced48b88238ac5abc7',
    messagingSenderId: '74651827398',
    projectId: 'flutter-projects-defcc',
    storageBucket: 'flutter-projects-defcc.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu4ePmf2Dxy4dZLD2wyE1T8dCudAt6wvc',
    appId: '1:74651827398:ios:b90c4719d6389b84c5abc7',
    messagingSenderId: '74651827398',
    projectId: 'flutter-projects-defcc',
    storageBucket: 'flutter-projects-defcc.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
